### ISSUE TITLE
源地址可以多网段吗

### ISSUE THREAD

**Issue by itolallen** [joyanhui/ikuai-bypass#1]
爱快的docker和爱快不是一个网段的，主网段是192.168.1.0/24, docker网段是192.168.2.0/24,在源ip里可以设置2个网段吗？如果可以书写的格式是怎样的？

**Comment by joyanhui** [comment]
爱快内的docker默认可以访问爱快的面板，只需要吧 ikuai-url 修改:http://192.168.1.1 即可
如果要配置docker 分流， src-addr: 这设置为 192.168.2.2-192.168.2.254  如果同时要添加 192.168.1.x 的复制后面的段落

或者把 两个网段放到到一个分组里面 src-addr 更换为分组名称应该也可以（未测试,自己试试）

爱快的docker和kvm都比较难用，没必要死磕爱快。

**Comment by 598895191** [comment]
实测可以多网段的，只需要用“,”分开即可！比如：192.168.2.2-192.168.2.254,192.168.3.2-192.168.3.254
