### ISSUE TITLE
ikuai-bypass.exe 不能立刻执行吗？

### ISSUE THREAD

**Issue by 10807428** [joyanhui/ikuai-bypass#12]
2024/06/18 17:15:32 运行模式 cron 配置文件 ./config.yml
2024/06/18 17:15:32 cronA 模式,执行一次，然后进入定时执行模式
2024/06/18 17:15:32 已启动计划任务 0 7 * * *

上面代码的意思是自动定时到每天早上7点？（到了第二天早上7点也没有自动执行！）   我不能打开就立刻执行更新吗？ 应该怎么修改才能立刻执行呢？

**Comment by Q2297045667** [comment]
也不知道为什么我这都是下午的15点执行  你这应该也是
另外第一次运行是自动更新一次的

**Comment by 10807428** [comment]
> 也不知道为什么我这都是下午的15点执行 你这应该也是 另外第一次运行是自动更新一次的

应该做成，打开即可更新那种。我竟然运行了，为什么不让更新？ 逻辑不太对。 可以运行就立刻更新一次，之后就定时更新。

**Comment by joyanhui** [comment]
运行后立刻执行一次  使用的参数是  `-r cron `
cronAft 是启动，但是不执行。


详情可以查看描述文件

**Comment by joyanhui** [comment]
建议先用`-r once` 测试以下是否正常执行 再检查定时任务执行情况

**Comment by joyanhui** [comment]
经过检查没有马上执行是-m参数默认值问题导致的，已经修复。稍后会推送一个新版上来。
