### ISSUE TITLE
各位觉得这种模式可行吗

### ISSUE THREAD

**Issue by LuoXingchen935** [joyanhui/ikuai-bypass#13]
![image](https://github.com/joyanhui/ikuai-bypass/assets/42908923/a15c3a54-e1e4-4b39-925d-fba29f5a1c98)
想问问各位觉得这种可行吗？主要是考虑到下联设备和OP的转发回来都用LAN1的情况下，可能对LAN1的带宽不太友好

**Comment by HomeQi** [comment]
我的结构和你的类似，只要交换机流量不是特别猛，应该是没啥问题的，可以放心（我没直通，都能抗住）

**Comment by LuoXingchen935** [comment]
> 我的结构和你的类似，只要交换机流量不是特别猛，应该是没啥问题的，可以放心（我没直通，都能抗住）

好的，感谢
