### ISSUE TITLE
端口分流问题

### ISSUE THREAD

**Issue by HomeQi** [joyanhui/ikuai-bypass#14]
**简单描述**
看config中端口分流下，感觉流量的出口是不是有点问题？不知道是否是我的理解问题，希望大佬能给解惑一下，非常感谢！
**运行环境**
爱快版本：免费版本3.7.12 x64
ikuai-bypass版本：v2.0.0 beta1
ikuai-bypass运行环境： linux
ikuai-bypass运行环境：amd64
**日志代码或截图支持md格式**
```sh
stream-ipport:      # 端口分流，与IP分组组合使用
  - type: 0 # 分流方式：0-外网线路，1-下一跳网关
    interface: wan2 # 分流线路（此处问题，国内IP为目标地址，应该是走wan1作为目标接口？）
    src-addr: 10.1.1.10-10.1.1.254   # 分流的源地址
    ## 域名列表网址，每行一个，超过1000行会自动分为多个
    ip-group: 国内 # 前面填写的IP分组名称，多个用逗号隔开
  - type: 1 # 分流方式：0-外网线路，1-下一跳网关
    nexthop: 10.1.1.2 # 下一跳网关
    src-addr: 10.1.1.10-10.1.1.254
    ip-group: Telegram
```

**Comment by HomeQi** [comment]
还有就是自定义运营商这里的telegram和Google的数据是不是没有用到呀？
```
custom-isp:     # 自定义运营商  IP分流
  - name: 国内IP列表  # 自定义运营商名称
    ## 自定义运营商 cidr 列表网址，每行一个，超过5000行会自动分为多个，ipv6 地址会被删除 
    ## 下面演示规则使用了ghproxy.com的代理，如果失效请自行更换或另外想办法，建议使用https://github.com/hunshcn/gh-proxy自建
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cn.txt
    tag: ipcn # 规则的备注标签后缀 如果留空默认为自定义运营商名称
  - name: telegram
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/telegram.txt
    tag: iptg
  - name: google
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/google.txt
    tag: ipgoogle
``` bash

**Comment by HomeQi** [comment]
还有就是执行命令后没有更新相关的规则？具体如图下所示
<img width="684" alt="image" src="https://github.com/joyanhui/ikuai-bypass/assets/54731976/9b897bd2-c2f2-4287-b702-dc3b0e3d0d1c">
但是执行 ```sh /opt/ikuai-bypass -r cron -c /opt/ikuai-bypass.yml -m ii ```的时候就会更新所有的数据了，不知道大佬是如何设计的？
目前我把service的脚本改为了 ```sh /opt/ikuai-bypass -r cronAft  -c /opt/ikuai-bypass.yml -m ii > /dev/null 2>&1 & ```
不知道这样是否可以？

**Comment by HomeQi** [comment]
> 还有就是执行命令后没有更新相关的规则？具体如图下所示 <img alt="image" width="684" src="https://private-user-images.githubusercontent.com/54731976/342072868-9b897bd2-c2f2-4287-b702-dc3b0e3d0d1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNTU2OTgsIm5iZiI6MTcxOTE1NTM5OCwicGF0aCI6Ii81NDczMTk3Ni8zNDIwNzI4NjgtOWI4OTdiZDItYzJmMi00Mjg3LWI3MDItZGMzYjBlM2QwZDFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE1MDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNTA3MTcyNzdhNTdmNzUyN2ExZThlNjk4ZTJiODIzODI2OTJkMDViYjE1MjBlMTEwNzU5NTQ0ZTUyNmM2ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.azV2EIenjvQIbAVCNfSpFVdNXsoI-agxHPtB7siduDY"> 但是执行 `sh /opt/ikuai-bypass -r cron -c /opt/ikuai-bypass.yml -m ii `的时候就会更新所有的数据了，不知道大佬是如何设计的？ 目前我把service的脚本改为了 `sh /opt/ikuai-bypass -r cronAft -c /opt/ikuai-bypass.yml -m ii > /dev/null 2>&1 & ` 不知道这样是否可以？

我翻了一下之前的问题，应该就是#7 issue中大佬无法复现出来的问题。

**Comment by HomeQi** [comment]
> > 还有就是执行命令后没有更新相关的规则？具体如图下所示 <img alt="image" width="684" src="https://private-user-images.githubusercontent.com/54731976/342072868-9b897bd2-c2f2-4287-b702-dc3b0e3d0d1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNTU2OTgsIm5iZiI6MTcxOTE1NTM5OCwicGF0aCI6Ii81NDczMTk3Ni8zNDIwNzI4NjgtOWI4OTdiZDItYzJmMi00Mjg3LWI3MDItZGMzYjBlM2QwZDFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE1MDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNTA3MTcyNzdhNTdmNzUyN2ExZThlNjk4ZTJiODIzODI2OTJkMDViYjE1MjBlMTEwNzU5NTQ0ZTUyNmM2ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.azV2EIenjvQIbAVCNfSpFVdNXsoI-agxHPtB7siduDY"> 但是执行 `sh /opt/ikuai-bypass -r cron -c /opt/ikuai-bypass.yml -m ii `的时候就会更新所有的数据了，不知道大佬是如何设计的？ 目前我把service的脚本改为了 `sh /opt/ikuai-bypass -r cronAft -c /opt/ikuai-bypass.yml -m ii > /dev/null 2>&1 & ` 不知道这样是否可以？
> 
> 我翻了一下之前的问题，应该就是#7 issue中大佬无法复现出来的问题。

只要加入了-m参数后即可实现更新，测试后可用（建议大家不要两种都使用，会导致连接数飙升。。。亦或将导致网络崩溃）

**Comment by joyanhui** [comment]
经过检查没有马上执行是-m参数默认值问题导致的，已经修复。稍后会推送一个新版上来。
