### ISSUE TITLE
可不可以增加开关控制删除模式

### ISSUE THREAD

**Issue by Delyfeel** [joyanhui/ikuai-bypass#15]
**期望到效果和场景**
可不可以增加开关控制删除模式，比如先添加后删除维护列表或者先删除后添加维护列表
目前只能先添加后删除维护ikuai分流列表，导致跟ikuai各个列表里id数值不断增加，会不会运行一段时间后由于id数值达到峰值而添加失败呢？
![QQ截图20240625170834](https://github.com/joyanhui/ikuai-bypass/assets/32803963/a337f01b-c3eb-4c12-877c-20042ee39109)

至于先删除后添加可能遇到的删除后不添加维护列表问题
1.可以通过重试【看配置文件有这个功能】
2.先手动添加维护列表通过ikuai后添加规则生效机制，即使自动维护列表删除也不会导致全部失效，只会导致增量失效。

还有一点就是在op上程序运行时间和op时间不一致，程序运行在了标准时间上，而op为东八区时间，导致程序的定时也是按照标准时间定时运行的
> 
> 2024/06/25 09:23:21 端口分流== 添加端口分流 'wan1,wan2@国内' 成功
> 2024/06/25 09:23:21 once 模式 执行完毕自动退出
> [root@OpenWrt:05:23 PM ~] #

**Comment by joyanhui** [comment]
1、自定义删除模式功能 后面会考虑以下
2、时间问题，我最近会处理

**Comment by joyanhui** [comment]
旧规则删除顺序功能已添加

时间的时区问题导致的时间不一致的问题 未能复现
