### ISSUE TITLE
运行exe后打开爱快没有变化

### ISSUE THREAD

**Issue by xonec** [joyanhui/ikuai-bypass#16]
**简单描述**

**运行环境**
爱快版本：免费版本3.7.13 x64 Build202406212115
ikuai-bypass版本：v2.0.0-beta1
ikuai-bypass运行环境： windows10
ikuai-bypass运行环境：amd64

修改config.yml中的爱快地址，账号密码后运行exe（cron: 51 4 * * * ），打开爱快没有变化。

**Comment by joyanhui** [comment]
因为没有提供详细截图 和日志 没法判断 问题。

大概猜测是  v2.0.0-b1版本 需要强制 -m参数导致的，或者添加-m参数执行

请使用v1.xx版本 或者 v2.0.1-alpha2

**Comment by 10807428** [comment]
> 因为没有提供详细截图 和日志 没法判断 问题。
> 
> 大概猜测是 v2.0.0-b1版本 需要强制 -m参数导致的，或者添加-m参数执行 或使用v1.xx版本 或者 v2.0.1 后的版本

大概什么时候会更新v2.0.1的版本？ 这个月内会更新吗？

**Comment by isight** [comment]
ikuai升级最新版后，似乎不能直接登录设置了

**Comment by joyanhui** [comment]
@isight 您好 有问题请单开一个issues，详细描述问题提供对应的环境情况。不然不好检查。

**Comment by joyanhui** [comment]
> > 因为没有提供详细截图 和日志 没法判断 问题。
> > 大概猜测是 v2.0.0-b1版本 需要强制 -m参数导致的，或者添加-m参数执行 或使用v1.xx版本 或者 v2.0.1 后的版本
> 
> 大概什么时候会更新v2.0.1的版本？ 这个月内会更新吗？

[v2.0.1-alpha3](https://github.com/joyanhui/ikuai-bypass/releases/tag/untagged-11f9a7a1ee3a478b7acf)

**Comment by xonec** [comment]
https://github.com/joyanhui/ikuai-bypass/releases/tag/untagged-11f9a7a1ee3a478b7acf
404了

**Comment by joyanhui** [comment]
> https://github.com/joyanhui/ikuai-bypass/releases/tag/untagged-11f9a7a1ee3a478b7acf 404了

之前本地gitea同步问题导致github频繁自动删除Releases,已经修复。
