### ISSUE TITLE
建议：增加IPv6分组的功能，谢谢作者。

### ISSUE THREAD

**Issue by a11088** [joyanhui/ikuai-bypass#17]
由于运营商在大部分地区已经不提供IPV4公网，所以爱快开启了IPV6功能。
但是遇到一个问题：像泥视频，星视界这些外网视频网站，进去后会被cloudflare和cloudfront提示CN的IP。

**Comment by a11088** [comment]
期望到效果和场景
目前用这个方案：[爱快 & OpenWrt 分流拓扑](https://www.right.com.cn/forum/thread-8252571-1-1.html)，由于运营商在大部分地区已经不提供IPV4公网，所以爱快开启了IPV6功能。
但是遇到一个问题：像[泥视频](https://www.nivod.cc/)，[星视界](https://www.histar.tv/)这些外网视频网站，进去后会被[cloudflare](https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/text/cloudflare.txt)和[cloudfront](https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/text/cloudfront.txt)拦截，提示CN的IP。
所以要在IPv6分组里添加cloudflare或者cloudfront的IPV6IP，然后在安全设置 > ACL规则里添加阻断。

**Comment by joyanhui** [comment]
感谢您的建议
ikuai可以设置ipv4 优先，dns也可以优先ipv4，运营商是否分配独立的ipv4公网ip和您的描述无关。
cloudflare和cloudfront 的ipv6更新频率很低，建议手动添加。

所以暂时不会添加ipv6的分组和isp分流
