### ISSUE TITLE
想问问各位WAN2的OP V6开起来没问题嘛

### ISSUE THREAD

**Issue by VwEl** [joyanhui/ikuai-bypass#18]
我只要开启ipv6，在有新设备加入的情况下CPU就会暴增30°，造成网络缓慢。只能关闭op上的ipv6了

**Comment by joyanhui** [comment]
这个问题比较奇怪，而且看起来和ikuai-bypass仿佛是没有关联。 建议去对应的社区咨询。
我先关掉了。
