### ISSUE TITLE
请教一下DNS是如何设置的

### ISSUE THREAD

**Issue by xiaobaozi233** [joyanhui/ikuai-bypass#19]
我现在整个循环已经搭建好了并在局域网搭建了dns解析。

现在我电脑设置成局域网的dns服务器或运营商时，ikuai好像获取不到具体访问的域名。
也就无法实现通过域名来进行分流，只判断了是否是国内ip就全部丢给了openwrt，然后clash里全是ip地址也没有进行分流了，全走了缺省的规则。

请问一下如何解决这个问题？

**Comment by joyanhui** [comment]
完全没有看懂您的问题描述
你的问题似乎也和ikuai-Bypass无关
您似乎也搞错了http和tcp/ip协议的基本概念。

爱快分流 是先按照域名分流，域名没匹配到后，再通过爱快配置的dns来解析域名获得ip后再分流。

openwrt 拿到爱快分流过来的tcp/ip流量 里面也是携带域名信息的。 至于你的clash 没根据域名分流请检查你的clash的配置。



因为没看得懂你的问题，所以感觉你遇到的问题，是你自己搞混了概念，搞错了问题。

通常
爱快10.1.1.1 开启dns代理功能，然后上有dns配置为运营商的dns 223.5.5.5 或者自建的dns  例如 10.1.1.2。
如果有自建dns 已经做好分流，如mosdns,那么clash的上游dns 可以全部配置为msdns的地址10.1.1.2，或者爱快的地址10.1.1.1就可以了。
如果么有自建dns ，那么clash的dns 要分别配置 国内和 223.5.5.5境外的dns  1.1.1.1

正常情况也不需要额外的配置

如果搞不懂基本概念，建议先从最小化最简单化的网络开始

**Comment by xiaobaozi233** [comment]
当前的情况是我pc设置的dns地址不是爱快的地址，到爱快就没有域名了。

感谢解答，现在很明白了
我会尝试将所有dns地址设置成爱快，然后再开启dns代理。
