### ISSUE TITLE
能否增加一个端口分流

### ISSUE THREAD

**Issue by 598895191** [joyanhui/ikuai-bypass#2]
不想用运营商分流，想直接从端口分流，通过端口分流选择下一跳网关进入旁路有

**Comment by joyanhui** [comment]
暂时没有计划，因为这个工具的目的是  自动添加和定时更新 域名和远程服务器ip的分流规则，主要是解决ikuai做主路由的代理上网的。

内网ip和端口分流，ip范围和端口范围都不会太多，三五条规则的事情，手动添加就行了。
