### ISSUE TITLE
发现一个BUG，IP分组会在首行出现 “ IKUAI_BYPASS”字符

### ISSUE THREAD

**Issue by cenranc** [joyanhui/ikuai-bypass#22]
**简单描述**
发现一个BUG，IP分组会在首行出现 “ IKUAI_BYPASS”字符
执行命令为  /opt/ikuai-bypass -m ii -r 1 -c  /opt/config.yml
如果这个 “ IKUAI_BYPASS”标记是为了后续的更新删除，那么这个标记会不会影响ip分流的效果呢？如果影响可否将受影响的ip多复制一个

**运行环境**
爱快版本：免费版 3.7.14 x64 Build202408011011
ikuai-bypass版本：v2.0.0-beta1
ikuai-bypass运行环境： openwrt
ikuai-bypass运行环境：amd64
**日志代码或截图支持md格式**

务必提供 完整命令 配置文件 以及运行日志，否则很有可能无法判断问题

![image](https://github.com/user-attachments/assets/bd4848ee-bb27-4a7b-b804-6401aaf4c50f)
![image](https://github.com/user-attachments/assets/3d752d8f-b784-4bd1-8367-8da8a50e924f)

>

**Comment by joyanhui** [comment]
此问题确实存在，稍后会检查 尝试修复

**Comment by joyanhui** [comment]
首行添加的 IKUAI_BYPASS 字符 为备注，爱快支持这种格式，详情查看您第一张图下面的备注。
