### ISSUE TITLE
建议：这样的话，是不是更优化、简单一些

### ISSUE THREAD

**Issue by 18690819111** [joyanhui/ikuai-bypass#25]
**期望到效果和场景**
直接再ikuai里面安装docker的clash或者singbox？
但是docker没有那么多网卡。是不是有什么办法能解决一下？
能实现ikuai加自身的docker功能就解决的问题

**Comment by joyanhui** [comment]
docker运行 openwrt+clash/singbox/openclash 或者 docker 运行 随便一个linux 然后跑clash/singbox/shellclash都可以
ikuai-bypass 要处理的自动更新分流规则，和你的网络top结构无关。

具体用vm还是docker 或者lxc 或者物理机 ，和ikuai-bypass无关，建议去恩山讨论交流。
