### ISSUE TITLE
IP分组一直在查询

### ISSUE THREAD

**Issue by runishiwo** [joyanhui/ikuai-bypass#27]
**简单描述**

**运行环境**
爱快版本：3.7.14 x64 Build202408011011
ikuai-bypass版本：v2.0.1-alpha3
ikuai-bypass运行环境： esir大佬编译的io固件
ikuai-bypass运行环境：amd64
**日志代码或截图支持md格式**
用的下面的命令
./ikuai-bypass -c ikuai-bypass.yml -m ii

2024/09/28 03:01:46 运行模式 cron 配置文件 ikuai-bypass.yml
2024/09/28 03:01:46 cron 模式,执行一次，然后进入定时执行模式
2024/09/28 03:01:46 先 启动 ...  自定义isp和域名分流模式 模式
2024/09/28 03:01:46 再 启动 ... ip分组和下一条网关模式
2024/09/28 03:01:46 ikuai 登录成功 http://10.0.0.1
2024/09/28 03:01:46 域名分流== 正在查询  备注为: IKUAI_BYPASS_gfw 的域名分流规则
2024/09/28 03:01:46 运营商/IP分流== 正在查询  备注为: IKUAI_BYPASS_ipcn 的运营商配置规则
2024/09/28 03:01:46 运营商/IP分流== 获取准备更新的自定义运营商列表成功 国内IP列表 ipcn
2024/09/28 03:01:46 运营商/IP分流==  正在更新 国内IP列表 ipcn
2024/09/28 03:01:46 运营商/IP分流==  http.get ... https://raw.githubusercontent.com/mayaxcn/china-ip-list/master/chnroute.txt
2024/09/28 03:01:46 域名分流==  获取准备更新的域名列表成功 gfw
2024/09/28 03:01:46 域名分流==  正在更新 wan2 gfw 10.0.0.10-10.0.0.254
2024/09/28 03:01:46 域名分流==  http.get ... https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt
2024/09/28 03:01:46 域名分流==  wan2 gfw 获取到 6194 个域名
2024/09/28 03:01:46 域名分流==  1 / 7 wan2 gfw  正在添加 .... 
.2024/09/28 03:01:47 运营商/IP分流==  国内IP列表 ipcn  获取到 8658 个ip
2024/09/28 03:01:47 运营商/IP分流==  添加ip: 5000  个,等待 3s 秒继续处理
.2024/09/28 03:01:48 域名分流==  wan2 gfw  添加域名: 1000  个成功,等待 3s 秒继续处理
..2024/09/28 03:01:50 运营商/IP分流==  添加ip: 3658  个,等待 3s 秒继续处理
.2024/09/28 03:01:51 域名分流==  2 / 7 wan2 gfw  正在添加 .... 
..2024/09/28 03:01:53 运营商/IP分流== 添加自定义运营商'国内IP列表'成功
2024/09/28 03:01:53 运营商/IP分流== 删除旧的运营商列表成功 国内IP列表 ipcn
2024/09/28 03:01:53 运营商/IP分流== 更新完成 国内IP列表 ipcn
2024/09/28 03:01:53 运营商/IP分流== 正在查询  备注为: IKUAI_BYPASS_iptg 的运营商配置规则
2024/09/28 03:01:53 运营商/IP分流== 获取准备更新的自定义运营商列表成功 telegram iptg
2024/09/28 03:01:53 运营商/IP分流==  正在更新 telegram iptg
2024/09/28 03:01:53 运营商/IP分流==  http.get ... https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/telegram.txt
2024/09/28 03:01:53 运营商/IP分流==  telegram iptg  获取到 9 个ip
2024/09/28 03:01:53 运营商/IP分流==  添加ip: 9  个,等待 3s 秒继续处理
2024/09/28 03:01:53 域名分流==  wan2 gfw  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:01:56 运营商/IP分流== 添加自定义运营商'telegram'成功
2024/09/28 03:01:56 运营商/IP分流== 删除旧的运营商列表成功 telegram iptg
2024/09/28 03:01:56 运营商/IP分流== 更新完成 telegram iptg
2024/09/28 03:01:56 运营商/IP分流== 正在查询  备注为: IKUAI_BYPASS_ipgoogle 的运营商配置规则
2024/09/28 03:01:56 域名分流==  3 / 7 wan2 gfw  正在添加 .... 
2024/09/28 03:01:56 运营商/IP分流== 获取准备更新的自定义运营商列表成功 google ipgoogle
2024/09/28 03:01:56 运营商/IP分流==  正在更新 google ipgoogle
2024/09/28 03:01:56 运营商/IP分流==  http.get ... https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/google.txt
2024/09/28 03:01:57 运营商/IP分流==  google ipgoogle  获取到 585 个ip
.2024/09/28 03:01:57 运营商/IP分流==  添加ip: 585  个,等待 3s 秒继续处理
.2024/09/28 03:01:58 域名分流==  wan2 gfw  添加域名: 1000  个成功,等待 3s 秒继续处理
..2024/09/28 03:02:00 运营商/IP分流== 添加自定义运营商'google'成功
2024/09/28 03:02:00 运营商/IP分流== 删除旧的运营商列表成功 google ipgoogle
2024/09/28 03:02:00 运营商/IP分流== 更新完成 google ipgoogle
.2024/09/28 03:02:01 域名分流==  4 / 7 wan2 gfw  正在添加 .... 
..2024/09/28 03:02:03 域名分流==  wan2 gfw  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:02:06 域名分流==  5 / 7 wan2 gfw  正在添加 .... 
..2024/09/28 03:02:08 域名分流==  wan2 gfw  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:02:11 域名分流==  6 / 7 wan2 gfw  正在添加 .... 
...2024/09/28 03:02:14 域名分流==  wan2 gfw  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:02:17 域名分流==  7 / 7 wan2 gfw  正在添加 .... 
.2024/09/28 03:02:18 域名分流==  wan2 gfw  添加域名: 194  个成功,等待 3s 秒继续处理
...2024/09/28 03:02:21 域名分流== 添加域名分流 'wan2' 成功
2024/09/28 03:02:21 域名分流==  删除旧的运营商列表成功
2024/09/28 03:02:21 域名分流== 正在查询  备注为: IKUAI_BYPASS_private_bypass 的域名分流规则
2024/09/28 03:02:21 域名分流==  获取准备更新的域名列表成功 private_bypass
2024/09/28 03:02:21 域名分流==  正在更新 wan2 private_bypass 10.0.0.10-10.0.0.254
2024/09/28 03:02:21 域名分流==  http.get ... https://raw.githubusercontent.com/joyanhui/ikuai-bypass/main/private/bypass-domain-list.txt
2024/09/28 03:02:21 域名分流==  wan2 private_bypass 获取到 3 个域名
2024/09/28 03:02:21 域名分流==  1 / 1 wan2 private_bypass  正在添加 .... 
2024/09/28 03:02:21 域名分流==  wan2 private_bypass  添加域名: 3  个成功,等待 3s 秒继续处理
...2024/09/28 03:02:24 域名分流== 添加域名分流 'wan2' 成功
2024/09/28 03:02:24 域名分流==  删除旧的运营商列表成功
2024/09/28 03:02:24 域名分流== 正在查询  备注为: IKUAI_BYPASS_private_direct 的域名分流规则
2024/09/28 03:02:24 域名分流==  获取准备更新的域名列表成功 private_direct
2024/09/28 03:02:24 域名分流==  正在更新 wan1 private_direct 10.0.0.2-10.0.0.254
2024/09/28 03:02:24 域名分流==  http.get ... https://raw.githubusercontent.com/joyanhui/ikuai-bypass/main/private/direct-domain-list.txt
.2024/09/28 03:02:25 域名分流==  wan1 private_direct 获取到 44 个域名
2024/09/28 03:02:25 域名分流==  1 / 1 wan1 private_direct  正在添加 .... 
2024/09/28 03:02:25 域名分流==  wan1 private_direct  添加域名: 44  个成功,等待 3s 秒继续处理
...2024/09/28 03:02:28 域名分流== 添加域名分流 'wan1' 成功
2024/09/28 03:02:28 域名分流==  删除旧的运营商列表成功
2024/09/28 03:02:28 域名分流== 正在查询  备注为: IKUAI_BYPASS_cn 的域名分流规则
2024/09/28 03:02:28 域名分流==  获取准备更新的域名列表成功 cn
2024/09/28 03:02:28 域名分流==  正在更新 wan1 cn 10.0.0.2-10.0.0.254
2024/09/28 03:02:28 域名分流==  http.get ... https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/china-list.txt
.2024/09/28 03:02:29 域名分流==  wan1 cn 获取到 88202 个域名
2024/09/28 03:02:29 域名分流==  1 / 89 wan1 cn  正在添加 .... 
..2024/09/28 03:02:31 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:02:34 域名分流==  2 / 89 wan1 cn  正在添加 .... 
..2024/09/28 03:02:36 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:02:39 域名分流==  3 / 89 wan1 cn  正在添加 .... 
..2024/09/28 03:02:41 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:02:44 域名分流==  4 / 89 wan1 cn  正在添加 .... 
..2024/09/28 03:02:46 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:02:49 域名分流==  5 / 89 wan1 cn  正在添加 .... 
...2024/09/28 03:02:52 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:02:55 域名分流==  6 / 89 wan1 cn  正在添加 .... 
..2024/09/28 03:02:57 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:03:00 域名分流==  7 / 89 wan1 cn  正在添加 .... 
..2024/09/28 03:03:02 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:03:05 域名分流==  8 / 89 wan1 cn  正在添加 .... 
...2024/09/28 03:03:08 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:03:11 域名分流==  9 / 89 wan1 cn  正在添加 .... 
..2024/09/28 03:03:13 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:03:16 域名分流==  10 / 89 wan1 cn  正在添加 .... 
..2024/09/28 03:03:18 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:03:21 域名分流==  11 / 89 wan1 cn  正在添加 .... 
...2024/09/28 03:03:24 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:03:27 域名分流==  12 / 89 wan1 cn  正在添加 .... 
..2024/09/28 03:03:29 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:03:32 域名分流==  13 / 89 wan1 cn  正在添加 .... 
..2024/09/28 03:03:35 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:03:38 域名分流==  14 / 89 wan1 cn  正在添加 .... 
...2024/09/28 03:03:40 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:03:43 域名分流==  15 / 89 wan1 cn  正在添加 .... 
..2024/09/28 03:03:46 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:03:49 域名分流==  16 / 89 wan1 cn  正在添加 .... 
...2024/09/28 03:03:51 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:03:54 域名分流==  17 / 89 wan1 cn  正在添加 .... 
...2024/09/28 03:03:57 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:04:00 域名分流==  18 / 89 wan1 cn  正在添加 .... 
..2024/09/28 03:04:03 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:04:06 域名分流==  19 / 89 wan1 cn  正在添加 .... 
...2024/09/28 03:04:08 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:04:11 域名分流==  20 / 89 wan1 cn  正在添加 .... 
...2024/09/28 03:04:14 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:04:17 域名分流==  21 / 89 wan1 cn  正在添加 .... 
...2024/09/28 03:04:20 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:04:23 域名分流==  22 / 89 wan1 cn  正在添加 .... 
...2024/09/28 03:04:26 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:04:29 域名分流==  23 / 89 wan1 cn  正在添加 .... 
...2024/09/28 03:04:32 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:04:35 域名分流==  24 / 89 wan1 cn  正在添加 .... 
...2024/09/28 03:04:38 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:04:41 域名分流==  25 / 89 wan1 cn  正在添加 .... 
...2024/09/28 03:04:44 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:04:47 域名分流==  26 / 89 wan1 cn  正在添加 .... 
...2024/09/28 03:04:50 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:04:53 域名分流==  27 / 89 wan1 cn  正在添加 .... 
...2024/09/28 03:04:56 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:04:59 域名分流==  28 / 89 wan1 cn  正在添加 .... 
....2024/09/28 03:05:03 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:05:06 域名分流==  29 / 89 wan1 cn  正在添加 .... 
...2024/09/28 03:05:09 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:05:12 域名分流==  30 / 89 wan1 cn  正在添加 .... 
...2024/09/28 03:05:16 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:05:19 域名分流==  31 / 89 wan1 cn  正在添加 .... 
....2024/09/28 03:05:22 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:05:25 域名分流==  32 / 89 wan1 cn  正在添加 .... 
...2024/09/28 03:05:28 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:05:31 域名分流==  33 / 89 wan1 cn  正在添加 .... 
....2024/09/28 03:05:35 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:05:38 域名分流==  34 / 89 wan1 cn  正在添加 .... 
...2024/09/28 03:05:41 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:05:44 域名分流==  35 / 89 wan1 cn  正在添加 .... 
....2024/09/28 03:05:48 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:05:51 域名分流==  36 / 89 wan1 cn  正在添加 .... 
....2024/09/28 03:05:55 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:05:58 域名分流==  37 / 89 wan1 cn  正在添加 .... 
...2024/09/28 03:06:01 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:06:04 域名分流==  38 / 89 wan1 cn  正在添加 .... 
....2024/09/28 03:06:08 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:06:11 域名分流==  39 / 89 wan1 cn  正在添加 .... 
....2024/09/28 03:06:15 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:06:18 域名分流==  40 / 89 wan1 cn  正在添加 .... 
....2024/09/28 03:06:22 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:06:25 域名分流==  41 / 89 wan1 cn  正在添加 .... 
...2024/09/28 03:06:29 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:06:32 域名分流==  42 / 89 wan1 cn  正在添加 .... 
....2024/09/28 03:06:36 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:06:39 域名分流==  43 / 89 wan1 cn  正在添加 .... 
....2024/09/28 03:06:43 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:06:46 域名分流==  44 / 89 wan1 cn  正在添加 .... 
....2024/09/28 03:06:49 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:06:52 域名分流==  45 / 89 wan1 cn  正在添加 .... 
....2024/09/28 03:06:57 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:07:00 域名分流==  46 / 89 wan1 cn  正在添加 .... 
....2024/09/28 03:07:04 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:07:07 域名分流==  47 / 89 wan1 cn  正在添加 .... 
.....2024/09/28 03:07:11 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:07:14 域名分流==  48 / 89 wan1 cn  正在添加 .... 
....2024/09/28 03:07:18 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:07:21 域名分流==  49 / 89 wan1 cn  正在添加 .... 
....2024/09/28 03:07:25 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:07:28 域名分流==  50 / 89 wan1 cn  正在添加 .... 
.....2024/09/28 03:07:33 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:07:36 域名分流==  51 / 89 wan1 cn  正在添加 .... 
....2024/09/28 03:07:40 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:07:43 域名分流==  52 / 89 wan1 cn  正在添加 .... 
....2024/09/28 03:07:48 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:07:51 域名分流==  53 / 89 wan1 cn  正在添加 .... 
.....2024/09/28 03:07:56 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:07:59 域名分流==  54 / 89 wan1 cn  正在添加 .... 
.....2024/09/28 03:08:04 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:08:07 域名分流==  55 / 89 wan1 cn  正在添加 .... 
......2024/09/28 03:08:12 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:08:15 域名分流==  56 / 89 wan1 cn  正在添加 .... 
.....2024/09/28 03:08:20 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:08:23 域名分流==  57 / 89 wan1 cn  正在添加 .... 
.....2024/09/28 03:08:28 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:08:31 域名分流==  58 / 89 wan1 cn  正在添加 .... 
.....2024/09/28 03:08:36 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:08:39 域名分流==  59 / 89 wan1 cn  正在添加 .... 
......2024/09/28 03:08:45 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:08:48 域名分流==  60 / 89 wan1 cn  正在添加 .... 
.....2024/09/28 03:08:53 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:08:56 域名分流==  61 / 89 wan1 cn  正在添加 .... 
.....2024/09/28 03:09:02 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:09:05 域名分流==  62 / 89 wan1 cn  正在添加 .... 
......2024/09/28 03:09:10 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:09:13 域名分流==  63 / 89 wan1 cn  正在添加 .... 
.....2024/09/28 03:09:19 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:09:22 域名分流==  64 / 89 wan1 cn  正在添加 .... 
......2024/09/28 03:09:27 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:09:30 域名分流==  65 / 89 wan1 cn  正在添加 .... 
......2024/09/28 03:09:36 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:09:39 域名分流==  66 / 89 wan1 cn  正在添加 .... 
......2024/09/28 03:09:45 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:09:48 域名分流==  67 / 89 wan1 cn  正在添加 .... 
.....2024/09/28 03:09:54 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:09:57 域名分流==  68 / 89 wan1 cn  正在添加 .... 
......2024/09/28 03:10:02 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:10:05 域名分流==  69 / 89 wan1 cn  正在添加 .... 
......2024/09/28 03:10:11 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:10:14 域名分流==  70 / 89 wan1 cn  正在添加 .... 
......2024/09/28 03:10:20 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:10:23 域名分流==  71 / 89 wan1 cn  正在添加 .... 
......2024/09/28 03:10:29 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:10:32 域名分流==  72 / 89 wan1 cn  正在添加 .... 
......2024/09/28 03:10:39 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:10:42 域名分流==  73 / 89 wan1 cn  正在添加 .... 
.......2024/09/28 03:10:48 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:10:51 域名分流==  74 / 89 wan1 cn  正在添加 .... 
......2024/09/28 03:10:57 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:11:00 域名分流==  75 / 89 wan1 cn  正在添加 .... 
......2024/09/28 03:11:07 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:11:10 域名分流==  76 / 89 wan1 cn  正在添加 .... 
.......2024/09/28 03:11:16 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:11:19 域名分流==  77 / 89 wan1 cn  正在添加 .... 
......2024/09/28 03:11:26 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:11:29 域名分流==  78 / 89 wan1 cn  正在添加 .... 
.......2024/09/28 03:11:35 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:11:38 域名分流==  79 / 89 wan1 cn  正在添加 .... 
.......2024/09/28 03:11:45 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:11:48 域名分流==  80 / 89 wan1 cn  正在添加 .... 
.......2024/09/28 03:11:55 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:11:58 域名分流==  81 / 89 wan1 cn  正在添加 .... 
......2024/09/28 03:12:05 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:12:08 域名分流==  82 / 89 wan1 cn  正在添加 .... 
.......2024/09/28 03:12:14 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:12:17 域名分流==  83 / 89 wan1 cn  正在添加 .... 
.......2024/09/28 03:12:24 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:12:27 域名分流==  84 / 89 wan1 cn  正在添加 .... 
.......2024/09/28 03:12:35 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:12:38 域名分流==  85 / 89 wan1 cn  正在添加 .... 
.......2024/09/28 03:12:45 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:12:48 域名分流==  86 / 89 wan1 cn  正在添加 .... 
.........2024/09/28 03:12:57 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:13:00 域名分流==  87 / 89 wan1 cn  正在添加 .... 
........2024/09/28 03:13:07 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:13:10 域名分流==  88 / 89 wan1 cn  正在添加 .... 
.......2024/09/28 03:13:18 域名分流==  wan1 cn  添加域名: 1000  个成功,等待 3s 秒继续处理
...2024/09/28 03:13:21 域名分流==  89 / 89 wan1 cn  正在添加 .... 
......2024/09/28 03:13:27 域名分流==  wan1 cn  添加域名: 202  个成功,等待 3s 秒继续处理
...2024/09/28 03:13:30 域名分流== 添加域名分流 'wan1' 成功
2024/09/28 03:13:30 域名分流==  删除旧的运营商列表成功
.2024/09/28 03:13:30 ikuai 登录成功 http://10.0.0.1
2024/09/28 03:13:30 ip分组== 正在查询  备注为: IKUAI_BYPASS_ 的ip分组规则

>

**Comment by gjhwssg** [comment]
一样问题，我现在解决办法是更新前，执行一下删除命令再更新就行了

**Comment by MxxApp** [comment]
同样问题，我只使用Ip分组，也是提示ip分组== 正在查询 备注为: IKUAI_BYPASS_ 的ip分组规则，无法使用，另外ip分组添加tag无效，手动创建IP分组，备注是IKUAI_BYPASS_test，用清理模式指定tag  test只会清除自定义运营商和域名分流，IP分组不会被清理，希望作者，有时间修复一下

**Comment by joyanhui** [comment]
此处确实存在问题，正在检查，稍后新版会尝试修复。

**Comment by MxxApp** [comment]
> 此处确实存在问题，正在检查，稍后新版会尝试修复。

测试了新版本，可以添加ip分组，目前还存在问题，config中IP分组添加tag无效，添加的分组备注变成了IKUAI_BYPASS_测试1_0 IKUAI_BYPASS+IP分组名这种组合，并没有使用tag标签，另外可不可以，非-r clean模式时，也可以指定tag，不需要每次运行，都全部清除包含IKUAI_BYPASS备注的条目，而是只清除需要的，因为只需要更新特定备注的条目，现在运行是
Tips: 在添加之前会强制删除所有备注包含 IKUAI_BYPASS 字符的ip分组和端口分流，不受delOldRule参数影响
这是不是bug,还是改成这样了

**Comment by joyanhui** [comment]
> > 此处确实存在问题，正在检查，稍后新版会尝试修复。
> 
> 测试了新版本，可以添加ip分组，目前还存在问题，config中IP分组添加tag无效，添加的分组备注变成了IKUAI_BYPASS_测试1_0 IKUAI_BYPASS+IP分组名这种组合，并没有使用tag标签，另外可不可以，非-r clean模式时，也可以指定tag，不需要每次运行，都全部清除包含IKUAI_BYPASS备注的条目，而是只清除需要的，因为只需要更新特定备注的条目，现在运行是 Tips: 在添加之前会强制删除所有备注包含 IKUAI_BYPASS 字符的ip分组和端口分流，不受delOldRule参数影响 这是不是bug,还是改成这样了

config中的对ip分组没有tag配置功能，目前的备注是  IKUAI_BYPASS_<分组名称>
并且添加之前会强制清理掉备注里面有 IKUAI_BYPASS 字符的ip分组和端口分流，在运行的时候已经有提示。并非bug,而且没有时间去做先查询添加后删除的逻辑，后面有时间会去处理一下。

后面一些文字，我无法理解您的意思，这个issues暂时关闭，有问题请重新开一个。
