### ISSUE TITLE
建议：我用了bypass以后观察了很久，并没有发现很明显的转发到爱快直连

### ISSUE THREAD

**Issue by Sour999** [joyanhui/ikuai-bypass#28]
**期望到效果和场景**
反而我在协议分流那，使用爱快自带的协议分流，很快就可以把一些内容分流到爱快直连那边。

**Comment by Sour999** [comment]
有一个问题就是事实上如果增加了IP分流，爱快会默认把所有的域名解析，这样直接就相当于暴露DNS,我测试了一下果然如此，把这个关闭了就没有暴露了

**Comment by joyanhui** [comment]
关于ikuai 分流规则的的优先级，建议去ikuai社区讨论。

至于暴露dns 不知道您所指的什么。

我暂时关闭这个issues,如果有其他和ikuai-bypass相关的问题，请重开

**Comment by joyanhui** [comment]
至于暴露dns 不知道您所指的什么。如果是说 ikuai 默认走udp请求公共dns，自己搭建一个dns 上游指定doh dot的dns即可解决，并在爱快内配置dns即可。

关于ikuai 分流规则的的优先级，以及爱快的使用问题，建议去ikuai社区或者恩山之类的社区讨论。

此问题和ikuai-bypass无关，

我暂时关闭这个issues,如果有其他和ikuai-bypass相关的问题，请重开

**Comment by refined-fish** [comment]
> 有一个问题就是事实上如果增加了IP分流，爱快会默认把所有的域名解析，这样直接就相当于暴露DNS,我测试了一下果然如此，把这个关闭了就没有暴露了

使用IP分流的必然结果，除非纯域名分流，但是你可以通过指定自建的DNS服务来避免泄露，设置好自己的DNS服务器防泄漏就可以了
