### ISSUE TITLE
更新成功后删除旧规则存在问题

### ISSUE THREAD

**Issue by blueberry-pie-11** [joyanhui/ikuai-bypass#3]
例如自定义运营商，如果只设置一个中国列表没问题。
但同时设置中国和Google两个运营商列表时，一旦其中一个更新成功但另一个失败，最后会导致所有旧规则列表都被删除。
建议备注使用 “IKUAI_BYPASS-中国”、“IKUAI_BYPASS-Google”这种形式区分是否删除旧列表

**Comment by joyanhui** [comment]
感谢建议，因为没遇到过单条记录更新失败的情况，所以忽视了这个可能存在的问题。


后面会考虑在配置文件中单独配置备注名称的方式来处理。
