### ISSUE TITLE
 新版本 无法 正确添加端口分流规则

### ISSUE THREAD

**Issue by cenranc** [joyanhui/ikuai-bypass#30]
版本 v2.0.3-alpha1
使用ikuai-bypass -m ii -r 1 -c  /opt/config.yml 命令
新版本写入ip后，无法在端口分流正确的写入ip
<img width="800" alt="image" src="https://github.com/user-attachments/assets/86f8009f-7952-43e8-b17a-988c8b12ab2b">

**Comment by joyanhui** [comment]
确认问题存在，正在修复

**Comment by joyanhui** [comment]
已经修复，并在本地测试通过
请在https://github.com/joyanhui/ikuai-bypass/actions/runs/11176023136 完成后测试

本次修改改动了 config.yml的默认端口分流的wan2 为wan1 请注意检查和您top的一致性

**Comment by joyanhui** [comment]
因为沿用了上游的配置实例，所以默认的config.yml 有一些混乱。
我本人建议 wan1 做直连运营商，wan2 或 下级设备（下一跳网关）处理网络深造问题。
建议修改为：
ip分组==国内： 既国内ip段 
非国内ip 例如github  google等 下一跳到 openwrt等深造网
手动添加一个 默认下一条到 openwrt的端口分流规则，备注中不要出现 IKUAI_BYPASS 字符
