### ISSUE TITLE
建议：加规则

### ISSUE THREAD

**Issue by 18690819111** [joyanhui/ikuai-bypass#32]
爱快本身的使用问题，还有网络top结构问题，在移步 爱快官方论坛或恩山或者discussions  https://github.com/joyanhui/ikuai-bypass/discussions

**期望到效果和场景**
你好，希望加一条PT的规则。避免PT、BT走了代理

**Comment by joyanhui** [comment]
您好，在 https://github.com/joyanhui/ikuai-bypass/blob/main/private/direct-domain-list.txt  这里规则里面底部有一部分Missing_Love维护的域名规则，添加了一些bt站点。
如果您的bt站点不再里面，请自己维护一个 域名列表。

另外在爱快里面用端口分流，可以让常用端口例如80 443等直接走wan1 其他端口按照ip/域名规则来处理。
