### ISSUE TITLE
crontab任务时间异常问题

### ISSUE THREAD

**Issue by HomeQi** [joyanhui/ikuai-bypass#33]
**简单描述**
1. cron表达式时间错误，OpenWrt时区设置正常，但执行时间相差8小时。

**运行环境**
爱快版本：免费版本3.7.15 x64 Build202409251708
ikuai-bypass版本：v2.1.2-Alpha1
ikuai-bypass运行环境： ImmortalWrt 23.05.4 r28061-399f9a1db3 / LuCI openwrt-23.05 branch git-24.265.44782-0ff45d8
ikuai-bypass运行环境：amd64
**日志代码或截图支持md格式**
<img width="584" alt="image" src="https://github.com/user-attachments/assets/c69b5e2d-89ae-4ae3-9d4d-b94642d32e53">

>

**Comment by HomeQi** [comment]
尝试了几种方法，时区问题依旧无法解决，如果可以希望能提供解决方法，非常感谢！
<img width="683" alt="image" src="https://github.com/user-attachments/assets/847d640b-4c90-4c32-b506-0d55588e34a7">
<img width="523" alt="image" src="https://github.com/user-attachments/assets/4a4775bf-1f1b-489f-ae87-b5952763f7b2">
<img width="274" alt="image" src="https://github.com/user-attachments/assets/acedf29c-dfb4-4bf6-9b7c-c06b42e66399">
ikuai已经开启了ntp服务，时间没有问题，我不太懂项目是如何进行定时执行任务的，尝试过在init.d/ikuai-bypass下添加export TZ='Asia/Shanghai'参数，经测试无效。

**Comment by HomeQi** [comment]
时区问题经过安装zoneinfo-asia后得到解决！

**Comment by refined-fish** [comment]
> 时区问题经过安装zoneinfo-asia后得到解决！

感觉不是一个最好的解决方案，如果项目本身能直接使用系统时间是比较方便的，使用难度也会下降
