### ISSUE TITLE
openrwrt 突然无法登录

### ISSUE THREAD

**Issue by nccstar** [joyanhui/ikuai-bypass#35]
**简单描述**
请描述清楚问题，并点亮star支持本项目。
文末最好提供完整运行命令和日志，以及配置文件的核心内容
请勿在旧的issue中提交新issue.

**运行环境**
爱快版本：免费版本3.7.15 x64 
ikuai-bypass版本：v2.1.2
ikuai-bypass运行环境： openwrt23.05
**日志代码或截图支持md格式**

root@ImmortalWrt:/opt# ./ikuai-bypass
2024/11/04 13:59:12 运行模式 cron 配置文件 ./config.yml
2024/11/04 13:59:12 cron 模式,执行一次，然后进入定时执行模式
2024/11/04 13:59:12 启动 ... 自定义isp和域名分流模式 模式
2024/11/04 13:59:22 ikuai 登陆失败： http://10.10.70.1 Post "http://10.10.70.1/Action/log                                                          in": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2024/11/04 13:59:22 登录爱快失败： Post "http://10.10.70.1/Action/login": context deadlin                                                          e exceeded (Client.Timeout exceeded while awaiting headers)
2024/11/04 13:59:22 已启动计划任务 0 7 * * *

同样的配置文件在openwrt中 昨天运行时好好的，今天突然报错 ，然后把配置文件在windows下运行可以正常执行

>

**Comment by joyanhui** [comment]
看日志是你op无法连接ikuai，ssh登陆到op，ping或者curl爱快的地址看看。
