### ISSUE TITLE
开机自动运行脚本运行无效

### ISSUE THREAD

**Issue by HomeQi** [joyanhui/ikuai-bypass#4]
试了很多种方法都不行，已经加过权限了。
<img width="789" alt="image" src="https://github.com/joyanhui/ikuai-bypass/assets/54731976/02b30126-ca63-4c49-9eac-732251daf53f">
贴一下我的配置信息，希望大佬看到能帮忙看一下，非常感谢！

**Comment by joyanhui** [comment]
你好，写了一个参考脚本。你可以直接复制里面的内容贴到ssh root@openwrt里面运行

[AddOpenwrtService.sh](https://github.com/joyanhui/ikuai-bypass/blob/main/script-example/AddOpenwrtService.sh)

**Comment by HomeQi** [comment]
新版本测试没有问题，可以完成开机自动启动！感谢老大
