### ISSUE TITLE
使用ispdomain模式，某些国内原本能用的服务会变得不好用

### ISSUE THREAD

**Issue by chris6868** [joyanhui/ikuai-bypass#42]
**简单描述**
在ispdomain模式下，苹果的appstore软件下载更新，不管国区还是外区，在梯子不好的情况下都会变慢，也就是都走了梯子，微软也是这样，哪怕手动添加了apple和微软的域名强制走wan1，但是其实还是会默认走wan2

**运行环境**
爱快版本：免费版3.7.16 x64 Build202411141700
ikuai-bypass版本：v2.1.2-alpha1
ikuai-bypass运行环境：debian12
ikuai-bypass运行环境：x86
**日志代码或截图支持md格式**

务必提供 完整命令 配置文件 以及运行日志，否则很有可能无法判断问题

爱快本身的使用问题，还有网络top结构问题，在移步 爱快官方论坛或恩山或者discussions  https://github.com/joyanhui/ikuai-bypass/discussions  

>

**Comment by chris6868** [comment]
修改成默认线路走wan1，然后gfw线路走wan2，就解决这个问题了，并且很好用

**Comment by joyanhui** [comment]
关于爱快分流的优先级顺序可以看下爱快官方文档。

**Comment by chris6868** [comment]
> 关于爱快分流的优先级顺序可以看下爱快官方文档。

这和分流优先级无关，主要是apple或微软不在国内的服务，但是国内直连是很好用的，但是使用分流后默认走wan2，如果梯子设置的非中国ip走梯子就会出现这个问题了
