### ISSUE TITLE
建议：能够处理带注释的域名/IP列表

### ISSUE THREAD

**Issue by refined-fish** [joyanhui/ikuai-bypass#48]
**期望到效果和场景**
程序能够处理带注释的域名/IP列表，方便维护规则
比如忽略以#开头的行
```
# Stun服务器
stun.syncthing.net
stun.hot-chilli.net
stun.fitauto.ru
stun.miwifi.com
```

**Comment by joyanhui** [comment]
因为不存在   `# Stun服务器`  这个域名 所以也不会影响实际使用效果。所以暂时不增加注释功能
具体参考 https://github.com/joyanhui/ikuai-bypass/blob/08e67c5edd0342e5e1e94ec15bd986aab47c8a01/private/direct-domain-list.txt#L23C1-L24C1

**Comment by refined-fish** [comment]
> 因为不存在 `# Stun服务器` 这个域名 所以也不会影响实际使用效果。所以暂时不增加注释功能 具体参考 https://github.com/joyanhui/ikuai-bypass/blob/08e67c5edd0342e5e1e94ec15bd986aab47c8a01/private/direct-domain-list.txt#L23C1-L24C1

懂了，用这种方式添加注释

**Comment by refined-fish** [comment]
> 因为不存在 `# Stun服务器` 这个域名 所以也不会影响实际使用效果。所以暂时不增加注释功能 具体参考 https://github.com/joyanhui/ikuai-bypass/blob/08e67c5edd0342e5e1e94ec15bd986aab47c8a01/private/direct-domain-list.txt#L23C1-L24C1

请问一下是否支持域名中带中文处理（也就是用中文写注释）
