### ISSUE TITLE
关于“ip分组+端口分流和下一跳网关”方式的默认配置文件的问题

### ISSUE THREAD

**Issue by jslyrd** [joyanhui/ikuai-bypass#49]
**简单描述**
首先，我想说明：1.我的目的是无感分流（下一跳网关方式），所以所有规则都不设置源ip（除旁路网关外）。2.根据爱快官网关于端口分流的描述，规则冲突的时候后添加的优先级高，不在规则里的话就走默认出口
因此，让旁路由走wan1（即避免死循环）的分流规则应该添加在最后，以防后添加的网段里含有它。注意，如果源ip为空，会匹配所有ip。
其次，走国内的规则应该添加在分流给旁路的规则后面，因为后添加的先生效，否则的话，如果像默认配置文件那样源ip一致（或不设置），将会导致以下问题：
    1.分配有目的ip，此时仅分配的目的ip会走旁路，这也是默认配置的情况
    2.未分配目的ip，此时所有流量都会走旁路
原配置（部分）如下：
```
ip-group:     # IP分组 和端口分流配合使用
  - name: 国内  # IP分组名称，分为多个时在名称后面拼接“序号”，如“国内_1”  因为爱快的ip分组没有备注功能，这里使用  IKUAI_BYPASS_<国内>_<01>来区分
    ## IP分组 cidr 列表网址，每行一个，超过1000行会自动分为多个，ipv6 地址会被删除
    url:  https://ghp.ci/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cn.txt
  - name: Telegram
    url:  https://ghp.ci/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/telegram.txt
stream-ipport:      # 端口分流，与IP分组组合使用
  - type: 0 # 分流方式：0-外网线路，1-下一跳网关
    interface: wan1 # 分流线路 这里默认到wan1 运营商
    src-addr: 192.168.1.10-192.168.1.254   # 分流的源地址  对应 ip-group: 国内 的目标地址
    ip-group: 国内
  - type: 1 # 分流方式：0-外网线路，1-下一跳网关
    nexthop: 192.168.1.2 # 下一跳网关  一般是openwrt地址
    src-addr: 192.168.1.10-192.168.1.254
    ip-group: Telegram
```
现在我测试能用的配置（部分）如下：
```
ip-group:     # IP分组 和端口分流配合使用
  - name: 国内  # IP分组名称，分为多个时在名称后面拼接“序号”，如“国内_1”  因为爱快的ip分组没有备注功能，这里使用  IKUAI_BYPASS_<国内>_<01>来区分
    ## IP分组 cidr 列表网址，每行一个，超过1000行会自动分为多个，ipv6 地址会被删除
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cn.txt
  - name: Telegram
    url:  https://127.0.0.1:2500 # https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/telegram.txt
stream-ipport:      # 端口分流，与IP分组组合使用
  - type: 1 # 分流方式：0-外网线路，1-下一跳网关
    nexthop: 172.16.6.9 # 下一跳网关  一般是openwrt地址
    ip-group: Telegram
  - type: 0 # 分流方式：0-外网线路，1-下一跳网关
    interface: wan1 # 分流线路 这里默认到wan1 运营商
    ip-group: 国内
  - type: 0 # 分流方式：0-外网线路，1-下一跳网关
    interface: wan1 # 分流线路 这里默认到wan1 运营商
    src-addr: Route
    ip-group: Telegram
```
我将Telegram组的url设置为一个获取不到的链接，这样telegram组就为空
我最终的规则如下图所示：
![image](https://github.com/user-attachments/assets/7ce72181-4a04-421c-b079-24acaa0e3def)
流量规则为：旁路网关ip直接走wan，优先级最高。其次为国内ip。其余的走旁路。

希望能修改默认规则，同时这个issue也给后面的人参考参考

**Comment by refined-fish** [comment]
这么说倒也是，存在优先级问题，建议你用自定义运营商分流方式，还能故障切换呢，下一跳网关寄了就全丢了

**Comment by refined-fish** [comment]
你重新用markdown编辑一下你的文本吧，看着太费劲了，代码用
```
括起来
```

**Comment by jslyrd** [comment]
> 你重新用markdown编辑一下你的文本吧，看着太费劲了，代码用
> 
> ```
> 括起来
> ```

改了。自定义运营商分流要用多一个网口，有倒是有但是没插网线，周末回家再搞

**Comment by refined-fish** [comment]
> 改了。自定义运营商分流要用多一个网口，有倒是有但是没插网线，周末回家再搞

x86爱快可以虚拟机起一个openwrt，用虚拟网口就行，不浪费网口

**Comment by refined-fish** [comment]
不过其实，教程中的也没有问题，你有问题是因为你没有设置源IP，你这个算另一种方式，教程也没必要修改吧，可以添加说明把你这种不写源地址的方式补充上

**Comment by jslyrd** [comment]
> > 改了。自定义运营商分流要用多一个网口，有倒是有但是没插网线，周末回家再搞
> 
> x86爱快可以虚拟机起一个openwrt，用虚拟网口就行，不浪费网口

当初图占用低，加上底层用的esxi，所以安装32位爱快。
设置有源ip确实可以避免一些问题，但我感觉教程里的还是有点问题的
```
像默认配置文件那样源ip一致（或不设置），将会导致以下问题：
1.分配有目的ip，此时仅分配的目的ip会走旁路，这也是默认配置的情况
2.未分配目的ip，此时所有流量都会走旁路
```
这段描述对分配同样源地址的应该适用，因为按默认配置里的，如果都没匹配上，就全跑wan了，只有目的ip足够健壮时才有用

**Comment by jslyrd** [comment]
最简单的，假设来了一条google的ip，没写在目的ip里（只有telegram的规则），此时就会走默认的wan。因此，至少要将走旁路的规则中的目的ip置空，或设置得足够多

**Comment by refined-fish** [comment]
> 当初图占用低，加上底层用的esxi，所以安装32位爱快。

esxi底层那也一样的，创建一个openwrt虚拟机，然后虚拟交换机连接两台虚拟机就可以

> 这段描述对分配同样源地址的应该适用，因为按默认配置里的，如果都没匹配上，就全跑wan了，只有目的ip足够健壮时才有用

教程中的默认线路是直连，所以未匹配到的都会走直连，匹配的走旁路由，这其实没啥问题，这只是一个示例，你可以根据需求自己改，如果你需要尽可能保证代理，你可以采用默认线路改成代理，然后CN_IP（这个IP表就很健壮）分流直连，这样的效果是不错的，特定的国外域名想直连就配合域名分流。

**Comment by refined-fish** [comment]
> 最简单的，假设来了一条google的ip，没写在目的ip里（只有telegram的规则），此时就会走默认的wan。因此，至少要将走旁路的规则中的目的ip置空，或设置得足够多

因为教程只是一个示例，不是让抄作业的，只给了Telegram，你可以自己加

**Comment by refined-fish** [comment]
但还是那句话，建议运营商分流，端口分流下一跳网关设置起来维护更困难，而且不支持负载均衡和故障切换

**Comment by jslyrd** [comment]
> > 最简单的，假设来了一条google的ip，没写在目的ip里（只有telegram的规则），此时就会走默认的wan。因此，至少要将走旁路的规则中的目的ip置空，或设置得足够多
> 
> 因为教程只是一个示例，不是让抄作业的，只给了Telegram，你可以自己加

原来如此。回头就弄负载均衡。感谢解答

**Comment by refined-fish** [comment]
> > 因为教程只是一个示例，不是让抄作业的，只给了Telegram，你可以自己加
> 
> 原来如此。回头就弄负载均衡。感谢解答

那就把这个issue关了吧

**Comment by jslyrd** [comment]
根据你的这个项目方案和教程，我研究出了一个结合mosdns+fakeip分流的方案，并使用爱快下发备用dns作为故障转移，可以探讨一下：https://github.com/jslyrd/home_dns_config

**Comment by jslyrd** [comment]
> > 根据你的这个项目方案和教程，我研究出了一个结合mosdns+fakeip分流的方案，并使用爱快下发备用dns作为故障转移，可以探讨一下：https://github.com/jslyrd/home_dns_config
> 
> 你要达到的目的如果只是分流和去广告，mihomo就够了，套娃mosdns和adg的意义是什么
mosdns仅用于将流量进行国内外区分，把非国内域名转给clash，clash将这些域名的ip地址洗成内网ip，便于爱快区分，达到国内域名和ip只走爱快的目的。adg可有可无，用到的是他的开箱即用的dns缓存和去广告

**Comment by refined-fish** [comment]
> mosdns仅用于将流量进行国内外区分，把非国内域名转给clash，clash将这些域名的ip地址洗成内网ip，便于爱快区分，达到国内域名和ip只走爱快的目的。adg可有可无，用到的是他的开箱即用的dns缓存和去广告

1. 国内外流量区分，mihomo也可以做到，国内交给一批DNS，国外交给一批DNS
2. DNS缓存，你既然用爱快了，直接把缓存放在爱快就行
3. 去广告也是一样的，mihomo也可以去广告

**Comment by jslyrd** [comment]
> > mosdns仅用于将流量进行国内外区分，把非国内域名转给clash，clash将这些域名的ip地址洗成内网ip，便于爱快区分，达到国内域名和ip只走爱快的目的。adg可有可无，用到的是他的开箱即用的dns缓存和去广告
> 
> 1. 国内外流量区分，mihomo也可以做到，国内交给一批DNS，国外交给一批DNS
> 2. DNS缓存，你既然用爱快了，直接把缓存放在爱快就行
> 3. 去广告也是一样的，mihomo也可以去广告

1.我明白你说的意思了。clash本身的确能够区分域名给不同的dns上游，但是要让他仅对国外域名转换成fakeip就不行了，所以要前置一个mosdns让clash只负责国外域名解析。至于不使用fakeip，就只能采取你这个项目的方法，在爱快上维护域名。
2.我提出这个方案是采取了更适用于我当前环境的方式，本质上实现方式与你这个项目的一致，主要是讨论一下看有没有什么弊端

**Comment by refined-fish** [comment]
> 但是要让他仅对国外域名转换成fakeip就不行了

可以，filter加GEOsite@cn就行

> 至于不使用fakeip，就只能采取你这个项目的方法，在爱快上维护域名。

这个你说的是啥，另外这个爱快不是我的项目

**Comment by refined-fish** [comment]
> 主要是讨论一下看有没有什么弊端

我感觉就是非必要不要套太多娃，维护困难，也不容易跑起来

**Comment by jslyrd** [comment]
> 可以，filter加GEOsite@cn就行
> 
这个还真不知道
> > 至于不使用fakeip，就只能采取你这个项目的方法，在爱快上维护域名。
> 
> 这个你说的是啥，另外这个爱快不是我的项目
是指让爱快直接识别fakeip转给旁路处理，而不是在爱快上维护域名.
> 
> 我感觉就是非必要不要套太多娃，维护困难，也不容易跑起来
确实，现在先跑着，有啥问题再去优化

**Comment by refined-fish** [comment]
> > 可以，filter加GEOsite@cn就行
> 
> 这个还真不知道

> > 至于不使用fakeip，就只能采取你这个项目的方法，在爱快上维护域名。
>
>这个你说的是啥，另外这个爱快不是我的项目
>是指让爱快直接识别fakeip转给旁路处理，而不是在爱快上维护域名.

> > 我感觉就是非必要不要套太多娃，维护困难，也不容易跑起来
>
>确实，现在先跑着，有啥问题再去优化

你如果不会配置mihomo可以看我主页的项目，我里面写的默认就有fakeip-filter: geosite:cn，不过我默认是redir-host模式，因为这样爱快缓存的也是真实IP，mihomo离线不影响正常访问，也不需要在爱快上维护域名，默认线路设置成mihomo就行，大陆IP分流到直连

**Comment by jslyrd** [comment]
> > > 可以，filter加GEOsite@cn就行
> > 
> > 
> > 这个还真不知道
> 
> > > 至于不使用fakeip，就只能采取你这个项目的方法，在爱快上维护域名。
> > 
> > 
> > 这个你说的是啥，另外这个爱快不是我的项目
> > 是指让爱快直接识别fakeip转给旁路处理，而不是在爱快上维护域名.
> 
> > > 我感觉就是非必要不要套太多娃，维护困难，也不容易跑起来
> > 
> > 
> > 确实，现在先跑着，有啥问题再去优化
> 
> 你如果不会配置mihomo可以看我主页的项目，我里面写的默认就有fakeip-filter: geosite:cn，不过我默认是redir-host模式，因为这样爱快缓存的也是真实IP，mihomo离线不影响正常访问，也不需要在爱快上维护域名，默认线路设置成mihomo就行，大陆IP分流到直连

ok，我去瞅瞅
