### ISSUE TITLE
域名分流更新超时，能否延长超时判断时长

### ISSUE THREAD

**Issue by lumenofwhy** [joyanhui/ikuai-bypass#5]
![Snipaste_2024-03-22_03-16-40](https://github.com/joyanhui/ikuai-bypass/assets/112168810/f0c18889-87f9-455a-9902-76b7cb3d063c)

可以看到 ikuai 后台是一直在处理的

![Snipaste_2024-03-22_03-13-12](https://github.com/joyanhui/ikuai-bypass/assets/112168810/b7a0b57e-e10d-43d7-82c5-feffc3bc450f)

![Snipaste_2024-03-22_03-14-12](https://github.com/joyanhui/ikuai-bypass/assets/112168810/9ffadb2a-a7ff-4bc6-9620-aadd6e5ebe8b)

**Comment by joyanhui** [comment]
这个超时貌似是爱快返回。我看下怎么调整一下逻辑。

**Comment by lumenofwhy** [comment]
> 这个超时貌似是爱快返回。我看下怎么调整一下逻辑。

好的，感谢

**Comment by lumenofwhy** [comment]
> > 这个超时貌似是爱快返回。我看下怎么调整一下逻辑。
> 
> 好的，感谢

当我在 ikuai 管理页提交自己手动修改的 .csv 文件时，导入速度很快。可否增加命令行自定义选项，将新更新的文件导出成 .csv 文件以供备用。

**Comment by joyanhui** [comment]
爱快的的txt/csv 需要包含id，如果id冲突，导入的时候会有问题。处理这个id会复杂。

**Comment by lumenofwhy** [comment]
> 爱快的的txt/csv 需要包含id，如果id冲突，导入的时候会有问题。处理这个id会复杂。

我之前在导入前手动将所有的域名分流都删除了😂，可以当做备选方案，望接纳

**Comment by joyanhui** [comment]
删掉重新导入是一个不错的折中方案。导出txt/csv 功能 我后面有时间会搞一下。


我手上的爱快x64虚拟机调到单核心1G 也是添加的china-list.txt这个列表 没出现超时的，不太好测试。

稍后我推送一个测试版上来，您可以试试看。新加了两个参数在配置文件里面
1、AddErrRetryWait  失败后重试之前的等待时间
2、AddWait 成功后等待时间
这两个都是为了等待爱快释放性能出来继续处理。 如果有测试，期待您的反馈。

**Comment by joyanhui** [comment]
1.0.0-beta导出txt功能完成 命令格式，只能导出域名分流的运营商/ip分流  我看好像并不能批量导入，所以暂时不做了

```sh
./ikuai-bypass -r exportDomainTxt  -exportPath /home/yh -c ./config_example.yml
```

**Comment by lumenofwhy** [comment]
![Snipaste_2024-03-23_22-51-42](https://github.com/joyanhui/ikuai-bypass/assets/112168810/9eee9eb7-5346-4fff-942e-f260800e0be6)

增加 AddWait=3s 参数后测试仍然失败，此时并不是硬件的最高负载

-----

成功使用导出的 text 文件进行导入
![Snipaste_2024-03-23_23-19-49](https://github.com/joyanhui/ikuai-bypass/assets/112168810/f4d841c7-e8c3-4694-ad4d-acde19b1d0e7)

**Comment by joyanhui** [comment]
我再次测试了几次，超时是爱快返回的，好像没法修改。ikuai-bypass作为他api的客户端暂时没找到简单的解决方法。
我个人日常使用 是使用的 运营商/ip 分流和 gwf+  [/private](https://github.com/joyanhui/ikuai-bypass/tree/main/private) 的两个列表。

**Comment by lumenofwhy** [comment]
好的，感谢帮助，可以关闭 issue 了 ❤️
