### ISSUE TITLE
能否增加一个更新ikuai的IP分组的功能

### ISSUE THREAD

**Issue by sunshinehcyyy** [joyanhui/ikuai-bypass#7]
我目前使用的方案是ikuai给国内IP段分组，然后使用端口分流指向下一跳网关，个人目前使用这个方案是最简单且高效的，而且不需要浪费一个网口做WAN,就是更新国内IP组的时候不方便，能否增加一下相关功能呢？
我目前使用的方案的地址：https://www.right.com.cn/forum/thread-8288009-1-1.html
![171203t3g4vv42skf2g2s2](https://github.com/joyanhui/ikuai-bypass/assets/50049108/58cfb12f-9944-475d-b999-fcce44065643)
![171212xtqt3aakza6e08bw](https://github.com/joyanhui/ikuai-bypass/assets/50049108/973c5618-5aef-443f-a64c-fdd33942e404)

**Comment by MxxApp** [comment]
需求同样功能，希望作者大大更新，看到https://github.com/OLOrz996/ikuai-bypass更新了这个功能，但是不知道如何用

**Comment by sunshinehcyyy** [comment]
> 需求同样功能，希望作者大大更新，看到[OLOrz996/ikuai-bypass](https://github.com/OLOrz996/ikuai-bypass)更新了这个功能，但是不知道如何用

我看了一下你这个库，我告诉你怎么用吧。
你只需要写上
ip-group:     # IP分组
stream-ipport:      # 端口分流
这俩地方的配置就行了，【custom-isp】和【stream-domain】你可以直接删除掉了。
大致就是
## 爱快管理页面的 URL，结尾不要加 "/"，
## 如不填写，则使用第一个接口的网关地址作为爱快地址，
## 如果在爱快自带 docker 运行，网关就是爱快地址，可以不写
# ikuai-url: http://192.168.1.1 
username: admin # 爱快用户名
password: pass  # 爱快密码
cron: 0 4 * * * # 执行更新的周期 crontab
ip-group:     # IP分组
  - name: 国内  # IP分组名称，分为多个时在名称后面拼接“序号”，如“国内_1”
    ## IP分组 cidr 列表网址，每行一个，超过1000行会自动分为多个，ipv6 地址会被删除
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/text/cn.txt
  - name: Telegram
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/text/telegram.txt
stream-ipport:      # 端口分流，与IP分组组合使用
  - type: 0 # 分流方式：0-外网线路，1-下一跳网关
    interface: wan2 # 分流线路
    src-addr: 192.168.1.100-192.168.1.250   # 分流的源地址
    ## 域名列表网址，每行一个，超过1000行会自动分为多个
    ip-group: 国内 # 前面填写的IP分组名称，多个用逗号隔开
  - type: 1 # 分流方式：0-外网线路，1-下一跳网关
    nexthop: 192.168.1.2 # 下一跳网关
    src-addr: 192.168.1.100-192.168.1.250
    ip-group: Telegram
甚至于说端口分流你如果已经配置好了，你就直接不需要在配置文件里面写端口分流的部分了。

**Comment by MxxApp** [comment]
看到 ztc1997 那边今天更新了，docker镜像也更新了

**Comment by sunshinehcyyy** [comment]
> 看到 ztc1997 那边今天更新了，docker镜像也更新了

看了一下，他已经支持IP分组了，可以直接拉他的docker

**Comment by joyanhui** [comment]
收到，这几天会更新

**Comment by joyanhui** [comment]
已经上线了一个测试版，初步测试没有问题。
最近忙别的事情，没有时间详细测试，有问题请提issues

**Comment by samuelleung1009** [comment]
<img width="697" alt="截屏2024-06-10 下午10 01 19" src="https://github.com/joyanhui/ikuai-bypass/assets/88902396/01e114c2-0744-4081-b962-cc9f35419a38">
<img width="1052" alt="截屏2024-06-10 下午10 03 59" src="https://github.com/joyanhui/ikuai-bypass/assets/88902396/e366b563-aa67-4dd9-8546-2d2f809becd2">
请教一下大佬, 为什么我shell启动后打开爱快后ip分组並没有变化的??

**Comment by yeqiu233** [comment]
我也是运行后，爱快没有任何变化

**Comment by joyanhui** [comment]
@yeqiu233 @samuelleung1009  请详细描述环境和复现步骤，我这里没能复现问题。最好单独开一个issues

**Comment by uo201** [comment]
windows端运行v2.1.2-alpha1也没有任何变化，只想配置ip分组，端口分流和下一跳网关。

**Comment by uo201** [comment]
windows端运行v2.1.2-alpha1爱快配置也没有任何变化，只配置ip分组，端口分流和下一跳网关。
和[samuelleung1009]图2一样。删除了【custom-isp】和【stream-domain】。

**Comment by xihajim** [comment]
> > 我跟你一样的想法做端口分流，但是我从终端进行traceroute，直接到了爱快就断了，不跳到旁路由，问了爱快客服说爱快的端口分流只针对LAN到WAN的，下一跳不能从LAN出去，你是怎么实现的呢？
> 
> 必须把旁防放单独一个网段，并且关闭任何形式的硬件加速。或者給转发流量做masquerade（等价于lan到wan）。两者二选一。

https://www.right.com.cn/forum/thread-8288009-1-1.html贴主这个方案就是同网段的

**Comment by xihajim** [comment]
> > 我跟你一样的想法做端口分流，但是我从终端进行traceroute，直接到了爱快就断了，不跳到旁路由，问了爱快客服说爱快的端口分流只针对LAN到WAN的，下一跳不能从LAN出去，你是怎么实现的呢？
> 
> 必须把旁防放单独一个网段，并且关闭任何形式的硬件加速。或者給转发流量做masquerade（等价于lan到wan）。两者二选一。

https://www.right.com.cn/forum/thread-8288009-1-1.html 贴主就是同网段的

**Comment by xihajim** [comment]
> > > > 我跟你一样的想法做端口分流，但是我从终端进行traceroute，直接到了爱快就断了，不跳到旁路由，问了爱快客服说爱快的端口分流只针对LAN到WAN的，下一跳不能从LAN出去，你是怎么实现的呢？
> > > 
> > > 
> > > 必须把旁防放单独一个网段，并且关闭任何形式的硬件加速。或者給转发流量做masquerade（等价于lan到wan）。两者二选一。
> > 
> > 
> > https://www.right.com.cn/forum/thread-8288009-1-1.html 贴主就是同网段的
> 
> 1. 检察是否已关闭硬件加速等流卸载机制（必须）
> 2. 在joyanhui/ikuai-bypass这个项目，去程也是跨网段的
> 3. rp_filter、pbr状态检测：对的，你就同网段吧，转发流量一转一个不吱声
> 4. 我上面也说了，你要同网段也可以，那便是给去程流量做masquerade

同网段没毛病，之前我就是用的ROS开OSPF动态路由进行上行的同网段分流，旁路由直接单LAN也不做任何伪装，很稳定，审计数据也都正常，因为数据只是经过了一次同网段路由转发而已，源目都不变，只能说爱快这边可能实现不了这样的想法（静态路由测试下来可以，我手写脚本导入地址表到静态路由里测试了，但是joyanhui/ikuai-bypass没有更新静态路由表的功能，而爱快又不支持动态路由）
