### ISSUE TITLE
执行问题

### ISSUE THREAD

**Issue by shaoyufeng147** [joyanhui/ikuai-bypass#8]
**简单描述**

**运行环境**
爱快版本:3.7.11 x64 Build202403051040
ikuai-bypass版本：v2.0
ikuai-bypass运行环境： linux发行版名称和版本/windows11/macos14
ikuai-bypass运行环境：amd64/386/arm7/mips-softfloat/ppc64le
**日志代码或截图支持md格式**
```sh
# 运行日志
```
运行过程没有报错如截图所示
![Screenshot_20240607_065035_com deskangel daremote](https://github.com/joyanhui/ikuai-bypass/assets/49990329/20964fbe-cd4e-41bb-9ee3-4583eeffba5e)
但是，爱快端却无任何变化，包括登录记录都没有
能不能帮忙，没有日志，不知道啥原因

**Comment by shaoyufeng147** [comment]
已经解决了，但是不知道原因，跑了两个op，一个做Tailscale，一个作clash，在Tail的op上出现此问题，早上在calsh的OP上正常了

**Comment by LuoXingchen935** [comment]
老哥方便问下怎么解决的吗

**Comment by shaoyufeng147** [comment]
我把这个部署重新部署在了跑openclash的设备上了，个人觉得哈，可能是代理的问题，没有翻墙的话，那些配置文件下载不了

**Comment by LuoXingchen935** [comment]
好的
