### ISSUE TITLE
ikuai 启动命令问题

### ISSUE THREAD

**Issue by Q2297045667** [joyanhui/ikuai-bypass#9]
**简单描述**
如下图配置之后启动失败
想问一下这个入口命令是不是我写错地方了？
这个命令在控制台是可以正常执行的
![image](https://github.com/joyanhui/ikuai-bypass/assets/42416195/c0eabe47-8ea7-4fd0-84f4-11ee872b76df)

**运行环境**
爱快版本：免费版本3.7.12 x64 Build202406112125
ikuai-bypass版本：v2.0.0-beta1
ikuai-bypass运行环境：alpine:latest)
ikuai-bypass运行环境：amd64
**日志代码或截图支持md格式**
![image](https://github.com/joyanhui/ikuai-bypass/assets/42416195/4a7a021e-bbc8-458b-931b-fbee6fa9a473)

```sh
# 运行日志
```

**Comment by Q2297045667** [comment]
最后使用 /opt/ikuai-bypass/ikuai-bypass -c /opt/ikuai-bypass/config.yml -r cron 启动成功

**Comment by joyanhui** [comment]
感谢您的贡献

**Comment by jright-hzxxg001** [comment]
大佬你的doc_docrek是配置什么网段，我的怎么配置都无法启动。
![屏幕截图 2024-06-30 154638](https://github.com/joyanhui/ikuai-bypass/assets/115604162/23e57039-fedc-4d26-9007-c2b01e090965)

**Comment by Q2297045667** [comment]
![Uploading QQ_1719739281225.png…]()

**Comment by Q2297045667** [comment]
> 大佬你的doc_docrek是配置什么网段，我的怎么配置都无法启动。 ![屏幕截图 2024-06-30 154638](https://private-user-images.githubusercontent.com/115604162/344450712-23e57039-fedc-4d26-9007-c2b01e090965.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3Mzk2MzUsIm5iZiI6MTcxOTczOTMzNSwicGF0aCI6Ii8xMTU2MDQxNjIvMzQ0NDUwNzEyLTIzZTU3MDM5LWZlZGMtNGQyNi05MDA3LWMyYjAxZTA5MDk2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQwOTIyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWNmNDRhNDY1MTg1ODQwZTk5Mzk1ZTEwM2ZmNzRkN2M4Yjc1MTA2MWYxNGI3NGY1ODUxMzFjYTRiMWI0ODgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VJmKbc1yZLE3DdZXMgJHb8xjbhL8EE3zFwlXWz1Id54)

![424FB2E20B4A7550D0D226427BD12097](https://github.com/joyanhui/ikuai-bypass/assets/42416195/45052ec4-913a-4713-a94c-a8016899b48e)
